rabbitmq:
  image: rabbitmq:3.8-management
  replicaCount: 1
  ports:
    amqp: 5672
    management: 15672
  volumeMounts:
    rabbitmqData:
      mountPath: /var/lib/rabbitmq
  persistentVolumeClaim:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 1Gi
